=== alumar8937/Reto1_Equipo3/XML/Empleados.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Departamentos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Departamento" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Empleados">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Empleado" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="Nombre" />
                          <xs:element type="xs:string" name="Apellido1" />
                          <xs:element type="xs:string" name="Apellido2" />
                          <xs:element type="xs:string" name="cuenta" />
                          <xs:element type="xs:date" name="Antigüedad" />
                          <xs:element type="xs:integer" name="N._de_afiliación_a_la_Seguridad_Social" />
                          <xs:element type="xs:string" name="Categoría-Grupo_profesional" />
                          <xs:element type="xs:byte" name="Grupo_Cotización" />
                          <xs:element type="xs:string" name="email" />
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="NIF" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="Nombre" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== alumar8937/Reto1_Equipo3/XML/Empleados.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- <!DOCTYPE Empleados SYSTEM "Empleados.dtd"> -->

<Empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="Empleados.xsd">
    <Empleado NIF="12345713-J">
        <Nombre>SUSANA</Nombre>
        <Apellido1>ALABAU</Apellido1>
        <Apellido2>SANCHO</Apellido2>
        <cuenta>salabaus</cuenta>
        <Antigüedad>27/03/2013</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>salabaus@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345704-A">
        <Nombre>LUIS</Nombre>
        <Apellido1>DEL TORO</Apellido1>
        <Apellido2>GIL</Apellido2>
        <cuenta>ldel_torog</cuenta>
        <Antigüedad>27/12/2020</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>ldel_torog@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345709-F">
        <Nombre>JUDAS</Nombre>
        <Apellido1>ISCARIOTE</Apellido1>
        <Apellido2>IMAN</Apellido2>
        <cuenta>jiscariotei</cuenta>
        <Antigüedad>5/10/2014</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>jiscariotei@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345710-G">
        <Nombre>TORIVIO</Nombre>
        <Apellido1>MARTINEZ</Apellido1>
        <Apellido2>INIESTA</Apellido2>
        <cuenta>tmartinezi</cuenta>
        <Antigüedad>2/06/2016</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>tmartinezi@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345702-Y">
        <Nombre>LAURA</Nombre>
        <Apellido1>MOLL</Apellido1>
        <Apellido2>GIL</Apellido2>
        <cuenta>lmollg</cuenta>
        <Antigüedad>27/12/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>lmollg@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345678-A">
        <Nombre>EVA</Nombre>
        <Apellido1>PELLICER</Apellido1>
        <Apellido2>JUAN</Apellido2>
        <cuenta>epellicerj</cuenta>
        <Antigüedad>16/03/2020</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>epellicerj@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345705-B">
        <Nombre>PEDRO</Nombre>
        <Apellido1>RAMIRES</Apellido1>
        <Apellido2>TORRES</Apellido2>
        <cuenta>pramirest</cuenta>
        <Antigüedad>7/10/2013</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>pramirest@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345706-C">
        <Nombre>LUCIA</Nombre>
        <Apellido1>VILA</Apellido1>
        <Apellido2>NOVA</Apellido2>
        <cuenta>lvilan</cuenta>
        <Antigüedad>18/06/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>lvilan@empresa3.com</email>
        <departamento>COMERCIAL</departamento>
    </Empleado>
    <Empleado NIF="12345680-C">
        <Nombre>JOHANN</Nombre>
        <Apellido1>AGUILAR</Apellido1>
        <Apellido2>ALBA</Apellido2>
        <cuenta>jaguilara</cuenta>
        <Antigüedad>16/10/2019</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>jaguilara@empresa3.com</email>
        <departamento>COMPATIBILITAT</departamento>
    </Empleado>
    <Empleado NIF="12345700-W">
        <Nombre>FRANCISCO</Nombre>
        <Apellido1>ANA</Apellido1>
        <Apellido2>CLETO</Apellido2>
        <cuenta>fanac</cuenta>
        <Antigüedad>1/03/2023</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>3</Grupo_Cotización>
        <email>fanac@empresa3.com</email>
        <departamento>COMPATIBILITAT</departamento>
    </Empleado>
    <Empleado NIF="12345679-B">
        <Nombre>RODRIGO</Nombre>
        <Apellido1>GALLEGO</Apellido1>
        <Apellido2>CHAVES</Apellido2>
        <cuenta>rgallegoc</cuenta>
        <Antigüedad>18/10/2013</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>rgallegoc@empresa3.com</email>
        <departamento>COMPATIBILITAT</departamento>
    </Empleado>
    <Empleado NIF="12345681-D">
        <Nombre>PEPE</Nombre>
        <Apellido1>SANCHO</Apellido1>
        <Apellido2>CARVALHO</Apellido2>
        <cuenta>psanchoc</cuenta>
        <Antigüedad>13/04/2019</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>psanchoc@empresa3.com</email>
        <departamento>COMPATIBILITAT</departamento>
    </Empleado>
    <Empleado NIF="12345707-D">
        <Nombre>ANDRES</Nombre>
        <Apellido1>BASE</Apellido1>
        <Apellido2>NOVA</Apellido2>
        <cuenta>abasen</cuenta>
        <Antigüedad>22/06/2015</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>abasen@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345701-X">
        <Nombre>MIGUEL</Nombre>
        <Apellido1>CID</Apellido1>
        <Apellido2>CABANES</Apellido2>
        <cuenta>mcidc</cuenta>
        <Antigüedad>26/03/2023</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>mcidc@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345684-G">
        <Nombre>FRANCISCO</Nombre>
        <Apellido1>COELLO</Apellido1>
        <Apellido2>ALABAU</Apellido2>
        <cuenta>fcoelloa</cuenta>
        <Antigüedad>28/03/2014</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>fcoelloa@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345683-F">
        <Nombre>ISABEL</Nombre>
        <Apellido1>RUIZ</Apellido1>
        <Apellido2>MONCHO</Apellido2>
        <cuenta>iruizm</cuenta>
        <Antigüedad>11/10/2014</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>iruizm@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345696-S">
        <Nombre>ALBERTO</Nombre>
        <Apellido1>SACA</Apellido1>
        <Apellido2>RINO</Apellido2>
        <cuenta>asacar</cuenta>
        <Antigüedad>4/11/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>1</Grupo_Cotización>
        <email>asacar@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345715-L">
        <Nombre>PIEDAD</Nombre>
        <Apellido1>VALENCIA</Apellido1>
        <Apellido2>RUIZ</Apellido2>
        <cuenta>pvalenciar</cuenta>
        <Antigüedad>11/12/2019</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>pvalenciar@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345682-E">
        <Nombre>SARA</Nombre>
        <Apellido1>ZAMBUJO</Apellido1>
        <Apellido2>CAMPOS</Apellido2>
        <cuenta>szambujoc</cuenta>
        <Antigüedad>16/09/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>szambujoc@empresa3.com</email>
        <departamento>INFORMÀTICA</departamento>
    </Empleado>
    <Empleado NIF="12345717-N">
        <Nombre>JAVIER</Nombre>
        <Apellido1>ARIAS</Apellido1>
        <Apellido2>PUJOL</Apellido2>
        <cuenta>jariasp</cuenta>
        <Antigüedad>2/02/2018</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
